Cloudzero/cloudzero-charts

charts/cloudzero-agent/README.md
charts/cloudzero-agent/templates/secret.yaml
charts/cloudzero-agent/values.yaml

based on chart feedback, using one variable for secret generation, and improving error messages
no api key:
```
helm template cz-prom-agent ./  --set clusterName=cirrus-staging --set cloudAccountId=618300337335 --set host=dev-api.cloudzero.com
Error: execution error at (cloudzero-agent/templates/secret.yaml:11:12): An API key is required when not using an existing secret via the existingSecretName argument. …
```

[CP-18172][CP-18173] use single variable for secret generation, better error messages

---

charts/cloudzero-agent/README.md
charts/cloudzero-agent/values.schema.json

while a k8s cluster itself does not have a concept of naming, cloud providers and k8s management tools do. the naming requirements may vary between them, but RFC 1035 should be a good criteria for naming. really, we want to be permissive in what users name their clusters, but also make sure users don't enter totally invalid characters
https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#rfc- …

CP-18124: require clusterName to be RFC1123 compliant

---

charts/cloudzero-agent/templates/cm.yaml

This PR ensures that `cloudAccountId` is always a string. With the new changes, specifying a somewhat large integer results in:
``` bash
cloudzero-agent-server ts=2024-04-24T15:05:27.382Z caller=dedupe.go:112 component=remote level=info remote_name=e667d6 url="https://dev-api.cloudzero.com/v1/container-metrics?cluster_name=bdren-agent-operator&cloud_account_id=100023459849829342" msg="Done replaying WAL" …
```

CP-18243: Coerce cloudAccountId to String

---

charts/cloudzero-agent/CHANGELOG.md
charts/cloudzero-agent/templates/_helpers.tpl
charts/cloudzero-agent/templates/cm.yaml

we should use the `existingSecretName` as the secret external name
some examples:
```
helm template foo-agent ./  --set clusterName='foo' --set cloudAccountId=12345.321 --set existingSecretName=foobar | grep 'secret:' -A 1
secret:
secretName: foobar
```
without existing secret:
```
helm template foo-agent ./  --set clusterName='foo' --set cloudAccountId=12345.321 --set apiKey=foobar | grep 'secret:' -A 1 …
```

CP-18233: existingSecretName should be used in secretName

---

.github/workflows/build-and-publish-chart.yml
charts/cloudzero-agent/Chart.yaml

fixing GH action to update only the version of the agent and not the sub charts. also bumped the version number of the chart so it will match with main branch

Fix GH action

---

charts/cloudzero-agent/CHANGELOG.md
charts/cloudzero-agent/Chart.yaml
charts/cloudzero-agent/templates/_helpers.tpl

This PR addresses the failure of container metrics from being scraped. 
Using `helm template`, to validate that the `remote_write` regex list is formatted correctly:
After:
``` yaml
remote_write:
- url: 'https://api.cloudzero.com/v1/container-metrics?cluster_name=foo&cloud_account_id=100000'
authorization:
credentials_file: /etc/config/prometheus/secrets/value
write_relabel_configs:
- source_labels: [__name__] …
```

CP-19226: Merge Metric Lists Correctly 

---

charts/cloudzero-agent/CHANGELOG.md
charts/cloudzero-agent/Chart.yaml
charts/cloudzero-agent/templates/cm.yaml
charts/cloudzero-agent/templates/deploy.yaml
charts/cloudzero-agent/templates/secret.yaml
charts/cloudzero-agent/values.yaml

- users can now add annotations to the secret and configmap created by the agent chart
- duplicate resource block removed
- nodeselector field moved to correct place in values.yaml
- scrape config updated to drop unused metrics
Given the input file:
```yaml
prometheusConfig:
configMapAnnotations:
foo.bar/bat: baz
secretAnnotations:
this.is/cool: "true"
```
installing with:
```bash
helm upgrade --install cz-prom-agent ./ ... -f my-test-file.yaml
```
given annotations are set on the cm and secret:
```bash
kg cm cz-prom-agent-configuration -o yaml | grep -i annotations -A 4
annotations:
foo.bar/bat: baz
meta.helm.sh/release-name: cz-prom-agent
meta.helm.sh/release-namespace: default
```
```bash
kg secret cz-prom-agent-api-key -o yaml | grep metadata -A 6
metadata:
annotations:
this.is/cool: …
```

[CP-19222][CP-19262][CP-19313] add annotations to configmap and secret; remove duplicate resource block

---

.github/workflows/test-python.yml
charts/cloudzero-agent/Makefile
charts/cloudzero-agent/src/validate.py

This PR adds:
1. A check to the Makefile to ensure we have no formatting changes
2. A github pipeline to run the `makefile check`  target. 
This PR CI is the testing, however if you'd like to run it manually do the following:
```bash
git clone git@github.com:josephbarnett/cloudzero-charts.git cloudzero-charts-jb
cd cloudzero-charts-jb
git checkout CP-19161-ensure-we-have-good-testing-on-new-validator-code
act -j test_python 
```
Note, you will need docker, and [act utility](https://github.com/nektos/act) installed.
<details>
<summary>Manual Test Results</summary>
```bash
$ act -j test_python 
INFO[0000] Using docker host 'unix:///var/run/docker.sock', and daemon socket 'unix:///var/run/docker.sock' 
[has_changes/detection_rules/scanner] 🚀  Start image=catthehacker/ubuntu:act-latest …
```

Cp 19161 ensure we have good testing on new validator code

---

charts/cloudzero-agent/CHANGELOG.md
charts/cloudzero-agent/README.md
charts/cloudzero-agent/templates/cm.yaml
charts/cloudzero-agent/values.yaml

If a user wants to provide a custom scrape config, the current `configOverride` param forces them to also supply the remote_write config. This is doable, but requires the user to maintain a static version of the remote_write config. The `configOverride` should only overwrite the scrape_configs section
additionally, users can use the `scrapeJobs` array to add arbitrary scrape jobs
1. using helm template, …

CP-19767: only scrape config should be overwritten by configOverride, allows users to set individual jobs

---

.github/workflows/build-test-publish-image.yml
charts/cloudzero-agent/CHANGELOG.md
charts/cloudzero-agent/README.md
charts/cloudzero-agent/docs/cicd-chart-testing.md
charts/cloudzero-agent/src/validate.py
charts/cloudzero-agent/templates/cm.yaml
charts/cloudzero-agent/templates/deploy.yaml
charts/cloudzero-agent/tests/test_validations.py
charts/cloudzero-agent/values.schema.json
charts/cloudzero-agent/values.yaml

1. Region is now a required input parameter. This is necessary because without this, we might mis-identify a cluster, since there is nothing preventing the the same account ID and name across multiple regions. Therefore, this parameter enables CloudZero to distinguish between clusters.
2. Added a check in the initContainer validator which hits an endpoint which requires authorization. Thus, we can ensure the …

CP-19612: Update cloudzero-agent chart to include region parameter

---

.github/workflows/build-test-publish-image.yml
charts/cloudzero-agent/Chart.yaml
charts/cloudzero-agent/README.md
charts/cloudzero-agent/src/validate.py
charts/cloudzero-agent/templates/deploy.yaml
charts/cloudzero-agent/values.yaml

* Add override to values.yaml when user has KMS/NodeExporter deployed already (ie. local DNS value to use with validator script)
* Add `skip_validations` flag to allow PRs from forks to merge when `secrets` are not set
* Refactor `kms` and `pne` yaml blocks to avoid complicated helm `index .Values` logic (should be camelcase)
* update readme for configuring `serviceEndpoint` for KMS and NodeExporter

CP-19831 allow configurable KMS DNS values

---

charts/cloudzero-agent/README.md

Drew was worried that adding the examples for GCP and Alibaba will insinuate support. Valid point. This PR removes them (but keeps them in a comment for easy add next time)

Update README.md - remove reference to GCP and Alibaba

---

charts/cloudzero-agent/CHANGELOG.md
charts/cloudzero-agent/templates/_helpers.tpl
charts/cloudzero-agent/templates/cm.yaml
charts/cloudzero-agent/values.yaml

we scrape a fairly large amount of metrics and metric labels that we don't really need, which increases resource usage.
1. performance - in a load test, memory was reduced by ~50%, CPU usage unchanged
2. functional - asserted standard test workloads produced the same container data output via standard pipline

CP-19620: reduce amount of ingested metrics and metric labels

---

.github/workflows/build-and-publish-chart.yml
charts/cloudzero-agent/Chart.yaml

adding the `pull --rebase` to the second commit caused issues. reverting it here
I tested this by creating replica branches of main and gh-pages and making sure that the same change worked: https://github.com/Cloudzero/cloudzero-charts/actions/runs/9862680239/job/27233806359

[CP-19969] do not pull for gh pages update

---

.github/workflows/build-and-publish-chart.yml

Improved release workflow to do all the things.
```
act -j build-and-publish-chart  -a $GH_USER --secret GITHUB_TOKEN=$GH_PAT
```
Results

Cp 20006 improve cloudzero charts release workflow

---

.github/workflows/build-and-publish-chart.yml

This fixes an error occurring during the release workflow process which was not creating the tag based on the HEAD of `main`. 
Additionally this adds a change log to the release creation.
Tested using act (however only so much testing can be done) - it must run in CI
```
git push --set-upstream origin CP-20053-chart-release-using-wrong-version-in-package
```

CP 20053 fix chart release workflow to use correct version in packaging

---

charts/cloudzero-agent/Chart.yaml

The validator will pull in the `Chart Version` when a deployment occurs. It would be valuable to have a `dirty default` version on `develop` branch to ensure we can identify when a user deployed from source on `develop` branch versus from a tag.
This is valuable because develop is intended to be always moving, and partial changes which may not be ready for a release may be present making it hard to debug failures at the customer site.
Thus `0.0.0-dev` would tell us we are dealing with a development branch deployment in the telemetry sent from the validator.
Note - this value is overwritten by the actual release version in the release workflow
N/A

CP-20053: ensure we have an easy to ID version on develop branch

---

.github/workflows/build-and-publish-chart.yml

This change allows passing in a version such as `1.0.0` as the tag to use when creating the version of the chart.
TBD

CP-20053: allow version to be passed in during release

---

charts/cloudzero-agent/templates/validatorcm.yaml

1. Add verification check which runs `prometheus --version`, capturing output for telemetry.
2. Add addition of version for chart (if set) to telemetry report
* https://github.com/Cloudzero/cloudzero-agent-validator/pull/12
* **BEFORE**: https://github.com/Cloudzero/cloudzero-charts/actions/runs/9941476131/job/27460604939?pr=60
* **AFTER:** https://github.com/Cloudzero/cloudzero-charts/actions/runs/9941476131/job/27462215989
1. Configure value.yaml to use development build:
```yaml
validator:
serviceEndpoints:
kubeStateMetrics:
prometheusNodeExporter:
name: env-validator
image:
repository: ghcr.io/cloudzero/cloudzero-agent-validator/cloudzero-agent-validator
tag: dev-0ef023a402356389927658b421682203339d8e83
digest:
pullPolicy: Always
```
2. Install
3. Get logs after run:
```json
{ …
```

CP-20097 add prometheus version check

---

.github/workflows/build-and-publish-chart.yml
charts/cloudzero-agent/README.md

[we recently started requiring](https://github.com/Cloudzero/cloudzero-charts/commit/6eb776b7293e3ba2ae9345998f40c15e5fcab34a) that `cloudAccountId` be passed in as a string. however, our docs set this arg with `--set`, which will always interpret strings like "12345678910" as integers. we should use `--set-string` in our documentation so that users who are passing in the arg on the CLI and not in a separate …

[CP-20166] update docs to help the user pass cloudAccountId as a string

---

charts/cloudzero-agent/templates/_helpers.tpl
charts/cloudzero-agent/templates/cm.yaml
charts/cloudzero-agent/templates/deploy.yaml
charts/cloudzero-agent/templates/secret.yaml
charts/cloudzero-agent/templates/validatorcm.yaml
charts/cloudzero-agent/values.schema.json
charts/cloudzero-agent/values.yaml

users may want to manage secrets with Hashicrop Vault, which requires no k8s Secrets at all. instead, it injects secrets to the container filesystem based on an annotation. the filename and filepath that the secret is inject to is based on the annotation provided by the user. to allow users to use Vault, we need to allow arbitrary secret filepaths to be specified, and we need to allow users to deploy without …

[CP-20164] Allow users to set secret filepath and filename for agent server container

---

charts/cloudzero-agent/templates/_helpers.tpl

Standard labels related to the `kube_pod_lablels` metric are important to correct grouping, and dimension based reporting for kubernetes workloads. 
Previous to this change, this metric was silently not being sent by the agent, preventing such important correlation and cost attribution. 
This change fixes:
- small typo preventing added labels
- addition of standard app.kubernetes.io/* labels and k8s.app* labels. 
* [README exporting-pod-labels section](https://github.com/Cloudzero/cloudzero-charts/tree/develop/charts/cloudzero-agent#exporting-pod-labels)
<details>
<summary>Condition Reproduction / Testing</summary>
1. Deploy kubernetes cluster
2. Deploy the chart using the README including kube-state-metrics and node-exporter
3. On the DB side of Cloudzero - inspect metrics, looking for …

CP-20388 CP-20359 fix standard labels now showing up

---

charts/cloudzero-agent/README.md
charts/cloudzero-agent/templates/_helpers.tpl
charts/cloudzero-agent/values.yaml

This is a follow up to https://github.com/Cloudzero/cloudzero-charts/pull/64
---
Standard labels related to the `kube_pod_lablels` metric are important to correct grouping, and dimension based reporting for kubernetes workloads. 
Previous to this change, the default kube-state-metrics would not include any label whitelist preventing propagation of `kube_pod_labels`.
This change:
- adds default label whitelist
- updates readme instructions when using existing `kube-state-metrics` service. 
<details>
<summary>Condition Reproduction / Testing</summary>
1. Deploy kubernetes cluster
2. Deploy the chart using the README including kube-state-metrics and node-exporter
3. On the DB side of Cloudzero - inspect metrics, looking for `kube_pod_labels` metric.
**RESULT BEFORE**: No data found
**RESULTS …

CP 20388 improve kubernetes labels documentation

---

charts/cloudzero-agent/templates/_helpers.tpl
charts/cloudzero-agent/templates/cm.yaml
charts/cloudzero-agent/templates/validatorcm.yaml

1. Add `cleanString` helper to sanitize strings used as parameters
2. Sanitize the `cloudAccountId`, `host`, `clusterName`, and `region` before use
1. Deploy cluster using rancher
2. Apply chart using the following values.yaml overrides:
```yaml
cloudAccountId: |-
1234567890
clusterName: local-workshop-cirrus-rancher
region: us-east-2
existingSecretName: cz-api-token
kube-state-metrics:
enabled: false
prometheus-node-exporter:
enabled: false
validator:
serviceEndpoints:
kubeStateMetrics: kube-state-metrics.monitoring.svc.cluster.local:8080
prometheusNodeExporter: node-exporter-prometheus-node-exporter.monitoring.svc.cluster.local:9100
```
> Notice the intentional newlines added to cloudAccountId parameter above.
3. Apply:
```sh
helm install cloudzero-agent . -f  rancher-agent-values.yaml …
```

CP-20643 clean whitespace on cloudAccountId before use

---

charts/cloudzero-agent/values.yaml

we'd like to show an example of some reasonable labels to include by default, but we also don't want to include all labels for memory usage reasons.
testing in progress - testing by deploying the default and validating data pipeline for default tags.

CP-20612: do not export all pod and namespace labels by default

---

charts/cloudzero-agent/templates/validatorcm.yaml

Remove extra quotes from validator configMap template.
**TEST**
```sh
$ helm upgrade cloudzero-agent . -f /Users/joe.barnett/company/code/cloudzero-charts-training/guides/02-prom-discovery/cloudzero-agent-values.yaml --namespace $NS
Release "cloudzero-agent" has been upgraded. Happy Helming!
NAME: cloudzero-agent
LAST DEPLOYED: Fri Aug  9 16:56:34 2024
NAMESPACE: cloudzero
STATUS: deployed
REVISION: 2
TEST SUITE: None
```
**get pods**
```sh
$ k -n $NS get pods
NAME                                      READY   STATUS            RESTARTS   AGE
cloudzero-agent-server-5958489bdc-jpmcg   0/2     PodInitializing   0          15s
cloudzero-agent-server-688b446b5b-h7wb5   2/2     Running           0          143m
```
**output**
```json
$ k -n $NS logs -f -c env-validator …
```

CP-20848 remove quotes from ConfigMap creation

---

charts/cloudzero-agent/templates/cm.yaml
charts/cloudzero-agent/values.yaml

Updated scrape intervals to default to 120s
Added new values to set the scrap configs if desired as well.
--set prometheusConfig.globalScrapeInterval=30s 
--set prometheusConfig.scrapeJobs.kubeStateMetrics.scrapeInterval=45s 
--set prometheusConfig.scrapeJobs.cadvisor.scrapeInterval=50s 
run helm install commands to set various values for the above settings
i.e.
helm upgrade --install cz-agent …

updated scrape intervals to default to 120s

---

charts/cloudzero-agent/README.md

Fix documented recommended setting when using custom scrape configuration.
- [ x All active GitHub checks for tests, formatting, and security are passing

CP-21512 bugfix: remove service discovery reference for static target scrape configuration override example

---

.github/workflows/build-and-publish-chart.yml

This PR bumps the version of `upload-artifact` to prevent the Manual Release Pipeline Step from failing. Currently the project is two versions behind. 
Deprecation Warning for `v2` and `v3`:
https://github.com/actions/upload-artifact
- [n/a] I have added documentation for new/changed functionality in this PR

CP-22180: Bump Upload Artifact Version

---

.github/workflows/build-and-publish-chart.yml

This PR is a follow up to https://github.com/Cloudzero/cloudzero-charts/pull/80/files#diff-f7010773715e736f56597bc757055502aeac9d3c3b35f1c3df936862291a34a9R140. We don't need to bump the Github Release package as well.
Original PR: https://github.com/Cloudzero/cloudzero-charts/pull/80/files#diff-f7010773715e736f56597bc757055502aeac9d3c3b35f1c3df936862291a34a9R140

CP-22180 (part 2): Drop Github Release Package Version

---

.github/workflows/build-and-publish-beta-chart.yml

This PR modifies the description for the `version` input parameter to the Beta Chart Workflow. Users should be aware that the suffix `-beta` will be appended to the version specified.

CP-22609: Add Better Description for Beta Chart Workflow

---

.github/workflows/build-and-publish-beta-chart.yml

This PR modifies the the Beta Chart Release Workflow so that new `beta` tags are not marked as `latest`.

CP-22609: Do not mark Beta Charts as Latest

---

.github/workflows/build-and-publish-beta-chart.yml
charts/cloudzero-agent/BETA-INSTALLATION.md

- CP-23279: publish to beta directory to prevent harm for stable versions
- CP-23279 update beta installation instructions
TBD

CP-23279: separate beta helm repository from stable

---

charts/cloudzero-agent/README.md
charts/cloudzero-agent/templates/validatorcm.yaml
charts/cloudzero-agent/values.yaml
docs/releases/0.0.29-beta.md
docs/releases/0.0.30-beta.md

This PR does the following:
- enables the CloudZero KSM by default.
- Modifies the KSM annotations so as not to be discoverable by other  scrape jobs.
- Test Case 1: Validate that the CloudZero KSM is deployed with the correct name:
- Test Case 2: Validate that other observability services cannot scrape the CloudZero KSM, given the annotation change:
To test this, I installed vanilla Prometheus alongside the Agent in a cluster and checked the Prometheus UI to ensure the Target didn't appear. This was in fact the case.

CP-23051: Change default kube-state-metrics behavior to use Cloudzero subchart

---

.github/workflows/build-and-publish-beta-chart.yml

release docs are kept in charts/cloudzero-agent/docs/releases, but the beta release doc check checks at the top level.

[CP-22730] update doc location for doc check in beta release process

---

charts/cloudzero-agent/BETA-INSTALLATION.md
charts/cloudzero-agent/Chart.lock
charts/cloudzero-agent/Chart.yaml
charts/cloudzero-agent/README.md
charts/cloudzero-agent/templates/cm.yaml
charts/cloudzero-agent/values.yaml

This PR defines a static target for the CloudZero KSM. Typically this value is dynamically discovered by Prometheus, but given the CloudZero KSM disables discovery, we must explicitly define it. The `configmap` resolves to:
```
scrape_configs:
- job_name: cloudzero-service-endpoints # kube_*, node_* metrics
...
static_configs:
- targets:
- cz-prom-agent-kube-state-metrics.prom-agent.svc.cluster.local:8080   <-- Endpoint
```
We can validate that this is in fact the endpoint by running:
``` bash
kubectl run -i --tty --rm debug --image=busybox --restart=Never -- nslookup cz-prom-agent-kube-state-metrics.prom-agent.svc.cluster.local  
```

CP-23388: Define Static KubeStateMetrics Target Endpoint

---

charts/cloudzero-insights-controller/templates/init-job.yaml

some security policies do not allow using the default service account - this updates the init job to use the chart service account

CP-23426: use insights-controller service account for init job

---

charts/cloudzero-insights-controller/values.yaml

For HA for the insights-controller, increasing the replicacount should help us be resilient to pod restarts. we should probably add some pod anti affinities to keep pods from scheduling on the same node, and maybe even try to get them scheduling on nodes in different AZs, but I think this will do for now

CP-23465: increase default replica count for insights controller

---

.github/workflows/build-and-publish-beta-chart.yml

one more fix for doc path
fixes: https://github.com/Cloudzero/cloudzero-charts/actions/runs/11944320449/job/33295067334

[CP-22730] fix doc path on chart release

---

charts/cloudzero-agent/Chart.yaml
charts/cloudzero-agent/docs/releases/1.0.3-beta.md
charts/cloudzero-agent/templates/validatorcm.yaml
charts/cloudzero-agent/values.yaml
charts/cloudzero-insights-controller/Chart.yaml

This PR modifies the `kube_state_metrics_reachable` command by including the full list of KSM metrics passed by the chart, rather than the hardcoded subset used during testing.
The base branch is `feature/1.0.2-beta-release` since these changes will be for beta `1.0.3`.
**Testing**
Below is the output of the CloudZero Agent Server `post-start` job. If you notice, the logs outline the metrics being validated, eventually leading to a passing status for `kube_state_metrics_reachable`:
``` json
{
"level": "info",
"log_sequence": 1,
"msg": "Using endpoint URL: http://cloudzero-state-metrics.prom-agent.svc.cluster.local:8080/metrics",
"op": "ksm",
"time": "2024-12-03T21:52:29Z"
}
{
"level": "error",
"log_sequence": 2,
"msg": "Failed to fetch metrics on attempt 1: Get …
```

CP-23740 (Feature/1.0.3 beta release): Validate KSM Metrics at Install

---

.github/workflows/test-chart.yml
charts/cloudzero-agent/Chart.lock
charts/cloudzero-agent/Chart.yaml
charts/cloudzero-agent/README.md
charts/cloudzero-agent/configuration.example.yaml
charts/cloudzero-agent/templates/_helpers.tpl
charts/cloudzero-agent/templates/certificate.yaml
charts/cloudzero-agent/templates/clusterrole.yaml
charts/cloudzero-agent/templates/clusterrolebinding.yaml
charts/cloudzero-agent/templates/cm.yaml
charts/cloudzero-agent/templates/deploy.yaml
charts/cloudzero-agent/templates/init-job.yaml
charts/cloudzero-agent/templates/insights-deploy.yaml
charts/cloudzero-agent/templates/issuer.yaml
charts/cloudzero-agent/templates/secret.yaml
charts/cloudzero-agent/templates/service.yaml
charts/cloudzero-agent/templates/serviceaccount.yaml
charts/cloudzero-agent/templates/webhooks.yaml
charts/cloudzero-agent/values.yaml
charts/cloudzero-insights-controller/templates/init-job.yaml

There isn't a lot of benefit to having a subchart in the cloudzero-agent chart now that they're always used together. this PR does two things:
1. merges the insights-controller chart into the cloudzero-agent chart, and
2. renames the `tags` map to `insightsController`
todo

[CP-23429] merge insights-controller into main chart

---

charts/cloudzero-agent/README.md
charts/cloudzero-agent/configuration.example.yaml
charts/cloudzero-agent/templates/_helpers.tpl
charts/cloudzero-agent/templates/certificate.yaml
charts/cloudzero-agent/templates/issuer.yaml
charts/cloudzero-agent/templates/webhooks.yaml
charts/cloudzero-agent/values.yaml
charts/cloudzero-certificate/.helmignore
charts/cloudzero-certificate/Chart.yaml
charts/cloudzero-certificate/templates/NOTES.txt
charts/cloudzero-certificate/templates/_helpers.tpl
charts/cloudzero-certificate/templates/secret.yaml
charts/cloudzero-certificate/values.yaml

one part of the beta feedback was that relying on cert-manager is not always easy. cert-manager should still be the preferred approach, but we also want to provide a quick way for users to test. This PR adds a helm chart that generates a self signed cert for the webhook server

[CP-23428] add helm chart for creating cert

---

.github/workflows/build-and-publish-beta-chart.yml
charts/cloudzero-agent/README.md
charts/cloudzero-agent/docs/releases/1.0.0-beta-4.md
charts/cloudzero-agent/docs/releases/1.0.4-beta.md
charts/cloudzero-agent/templates/cm.yaml
charts/cloudzero-agent/values.yaml

- **CP-24028: add scrape target for insights container**
- **CP-22734: Bump insights image release version**
- **Enhance README for helm repo management**
- **Add release note for next beta version**
- **Update release process for customer version numbers in betas**
1. Deploy small cluster
```yaml
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
name: aws-cirrus-jb-insights-cluster
region: us-east-2
iam:
withOIDC: true
addons:
- name: vpc-cni
version: latest
- name: kube-proxy
version: latest
- name: coredns
version: latest
nodeGroups:
- name: ng-1
instanceType: t3.small
desiredCapacity: 2
volumeSize: 20
amiFamily: Bottlerocket
```
```sh
eksctl create cluster -f insights-cluster.yaml
```
2. Deploy cert manager
```sh
kubectl apply -f …
```

CP 24028 add insights controller scape config

---

charts/cloudzero-agent/docs/cert-trouble-shooting.md
charts/cloudzero-agent/docs/releases/1.0.0.md
charts/cloudzero-agent/values.yaml

* Release notes for 1.0.0 Release
* Troubleshooting guide for Certificates Issues
* Bump version of insights-controller image
N/A

CP-20221: Labels and Annotations

---

.github/workflows/build-and-publish-beta-chart.yml
charts/cloudzero-agent/README.md
charts/cloudzero-certificate/templates/_helpers.tpl

if we want to allow the user of the cloudzero-certificate chart, we need to publish it. this PR does that, as well as makes sure that multiple cases are coverage for the cert dns name
in progress

[CP-24423] update readme, add extra svc names to cloudzero-cert, add cloudzero-cert chart publish

---

.github/workflows/build-and-publish-beta-chart.yml

we no longer need this published

[CP-24668] remove cloudzero-certificate from beta workflow

---

charts/cloudzero-agent/docs/releases/1.0.0-beta-8.md
charts/cloudzero-agent/templates/_helpers.tpl
charts/cloudzero-agent/templates/deploy.yaml
charts/cloudzero-agent/templates/init-job.yaml
charts/cloudzero-agent/templates/insights-deploy.yaml
charts/cloudzero-agent/values.yaml

the init-cert job doesn't allow imagePullSecrets to be set. this fixes that, and also adds sensible default for all imagepullsecrets
**1. with only top level `imagePullSecrets` set, all resources should use that setting:**
given:
```yaml
imagePullSecrets:
- name: foobar
```
result:
```
helm template cloudzero-agent-with-ui ./ -f ~/dmepham/testing/danm-cluster.yaml | grep imagePullSecrets -A 1
imagePullSecrets:
- name: foobar
--
imagePullSecrets:
- name: foobar
--
imagePullSecrets:
- name: foobar
--
imagePullSecrets:
- name: foobar
```
**2. multiple secrets can be given**
given:
```yaml
imagePullSecrets:
- name: foobar
- name: batbaz
```
result:
```console
helm template cloudzero-agent-with-ui ./ -f ~/dmepham/testing/danm-cluster.yaml | grep imagePullSecrets -A 2
imagePullSecrets:
- name: …
```

CP-24743: allow all resources to use imagePullSecrets

---

charts/cloudzero-agent/docs/releases/1.0.0-beta-9.md
charts/cloudzero-agent/templates/cm.yaml
charts/cloudzero-agent/values.yaml

- allows the user to configure log level
- increases the default remote write timeout to 1m to allow for large clusters to be backfilled by default
with the following settings:
```yaml
insightsController:
server:
logging:
level: debug
send_interval: 10s
send_timeout: 2m
```
results
```console
kg cm cloudzero-agent-with-ui-webhook-configuration -o yaml | grep -E 'send_interval|send_timeout|level'
level: debug
send_interval: 10s
send_timeout: 2m
```
- debug logs in the webhook server pods (including scrape pod) are enabled
- send timeout is shown to be 2m during the scrape job

CP-24792: allow more configurable settings, increase default remote write timeout

---

charts/cloudzero-agent/README.md
charts/cloudzero-agent/docs/releases/1.0.0-beta-9.md
charts/cloudzero-agent/values.yaml

many users will be using a private image repo, and will need to get the images to mirror to their private image repo. adding the image information to the KSM subchart section will make this easier while not changing funcitonality
Before change:
```console
kg po cloudzero-agent-with-ui-cloudzero-state-metrics-569f756d86zcszc -o yaml | grep -i image
image: registry.k8s.io/kube-state-metrics/kube-state-metrics:v2.10.1
```
After change:
```console
kg pod cloudzero-agent-with-ui-cloudzero-state-metrics-569f756d86m85jj -o yaml | grep -i image
image: registry.k8s.io/kube-state-metrics/kube-state-metrics:v2.10.1
```
Note that there is no change in image reference

CP-24792: add KSM image info for easy identification of images to mirror for private image registries

---

charts/cloudzero-agent/docs/releases/1.0.0-beta-9.md
charts/cloudzero-agent/templates/_helpers.tpl
charts/cloudzero-agent/templates/validatorcm.yaml

Fixes an issue introduced in a recent beta version where the KSM address will be formed incorrectly if the full name override is not supplied
1. testing with no additional settings for KSM shows all required metrics in the prom ui
2. testing with
```yaml
kubeStateMetrics:
enabled: false
targetOverride: "indie-ksm-kube-state-metrics.kube-system.svc.cluster.local:8080"
```
shows all required metrics in the prom ui

CP-24833: template KSM service address using the release name

---

charts/cloudzero-agent/README.md

This PR fixes the [README](https://github.com/Cloudzero/cloudzero-charts/blob/develop/charts/cloudzero-agent/README.md#exporting-pod-labels) example for allowlisting pod labels. According to the [kube-state-metrics](https://github.com/kubernetes/kube-state-metrics/blob/main/docs/developer/cli-arguments.md) documentation, the syntax used in the example is invalid.

CP-24815 Fix KSM label allowlist syntax in README

---

charts/cloudzero-agent/templates/_helpers.tpl
charts/cloudzero-agent/templates/cm.yaml
charts/cloudzero-agent/templates/deploy.yaml
charts/cloudzero-agent/values.yaml

I also switched from a hardcoded value it to using `prometheusConfig.scrapeJobs.kubeStateMetrics.scrapeInterval` for the KSM job scrape_interval. This seems to pretty clearly be the intent of the configuration option, but it was not being used. Notably, this increases the interval from 1m to 2m.
>
> - …

CP-23129: add Prometheus scrape job to scrape metrics from itself

---

charts/cloudzero-agent/templates/_helpers.tpl

**Problem:**
When upgrading and updating the image used in the init scrape job, we can hit issues because the Job image field is immutable. this can be easily fixed by including a reference to the image tag and the chart version in the job name
another benefit is that we re-capture state on every upgrade, which is beneficial if we're adding bugfixes
**Example:**
install a chart:
```console
helm upgrade --install cloudzero-agent-with-ui cloudzero-beta/cloudzero-agent -f override.yaml --version 1.0.0-beta-10
Release "cloudzero-agent-with-ui" does not exist. Installing it now.
NAME: cloudzero-agent-with-ui
LAST DEPLOYED: Thu Jan 23 16:52:56 2025
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
```
then update it to use a new image version. this would most likely happen …

[CP-24912] use image tag and chart name in init job name

---

charts/cloudzero-agent/templates/_helpers.tpl
charts/cloudzero-agent/templates/init-job.yaml
charts/cloudzero-agent/values.yaml

"scrape" is a poor name here, since it is an overloaded term in the prometheus world. 
~The downside is that this would be a breaking change for users on the beta-9 through beta-10~
update: `initBackfillJob` is the documented field to use, but `initScrapeJob` can still be used as well. if both exist, `initBackfillJob` is given preference
1. validated that `initBackfillJob` and `initScrapeJob` can be used interchangeably and produce the same templated yaml
2. validated precedence rules. given the following input:
```yaml
initScrapeJob:
image:
repository: scrape.com/scrape
tag: 1.2.3
pullPolicy: Always
imagePullSecrets:
- name: foobar
initBackfillJob:
image:
repository: backfill.com/backfill
pullPolicy: Always
```
produces the following:
```yaml
apiVersion: batch/v1
kind: Job
metadata: …
```

[CP-24655] rename "scrape" to "backfill"

---

.github/workflows/build-and-publish-chart.yml

similar to https://github.com/Cloudzero/cloudzero-charts/pull/150, but doing it in the release branch because I forgot that the release needs release docs available, which are not available in `develop`

CP-25165: removing insights-controller refs in release branch

---

.github/workflows/build-and-publish-chart.yml

[CP-25165] allow non-main branch to run release workflow

---

.github/workflows/build-and-publish-chart.yml

moving the order of the steps so that we checkout the inputted branch before running

CP-25165: checkout correct branch before running release

---

.github/workflows/build-and-publish-chart.yml

CP-25165: checkout the input branch, not main, in release workflow

---

charts/cloudzero-agent/templates/cm.yaml
charts/cloudzero-agent/values.yaml

These are pretty much the minimal changes to allow us to point the agent at the collector.
>
> - Support forum thread
> - Related pull requests/issues from other repos
>
> If there are no references, simply delete this section.
Bascially, add this to your overrides:
```yaml
host: …
```

CP-25698: add ability to configure endpoint and scheme

---

charts/cloudzero-agent/README.md
charts/cloudzero-agent/docs/istio.md
charts/cloudzero-agent/templates/_helpers.tpl
charts/cloudzero-agent/templates/init-job.yaml
charts/cloudzero-agent/templates/webhooks.yaml
charts/cloudzero-agent/values.yaml

- fixing namespaceSelector indentation
- fix certificate update in particular upgrade path
- add istio documentation
1. namespaceSelector should be settable:
given:
```yaml
insightsController:
webhooks:
namespaceSelector:
matchExpressions:
- key: foo
operator: In
values:
- bar
```
and namespaces labeled accordingly:
```
kg ns -l foo=bar
NAME      STATUS   AGE
default   Active   253d
foobar    Active   13d
```
- pod creation in foobar/default namespaces shows activity ✅ 
- pod creation in non-foobar/default namespaces does not show activity ✅ 
2. fullnameOverride should working as expected
given:
```yaml
server:
fullnameOverride: "special-name"
```
resources are deployed accordingly and correctly:
```
special-name-698c667457-sx6zz                              2/2     Running     0 …
```

[CP-26202][CP-26358]: add istio doc, minor fixes/improvements

---

charts/cloudzero-agent/templates/_helpers.tpl
charts/cloudzero-agent/templates/aggregator-deploy.yaml
charts/cloudzero-agent/templates/cm.yaml
charts/cloudzero-agent/templates/deploy.yaml
charts/cloudzero-agent/templates/service.yaml
charts/cloudzero-agent/values.yaml

This adds the the aggregator to the helm chart.
>
> - Support forum thread
> - Related pull requests/issues from other repos
>
> If there are no references, simply delete this section.
To test, you'll need to specify a few values in an overrides file:
```yaml
aggregator:
enabled: true …
```

CP-25368, CP-25369, CP-25370, CP-25371: add aggregator to Helm chart

---

charts/cloudzero-agent/docs/releases/1.0.1.md
charts/cloudzero-agent/values.yaml

Added some more release notes for version 1.0.1 of the insights controller, that reference the changes made in [this release](https://github.com/Cloudzero/cloudzero-insights-controller/releases/tag/0.1.2).
- [Release 0.1.2 of the insights controller](https://github.com/Cloudzero/cloudzero-insights-controller/releases/tag/0.1.2)

CP-26389: More release notes for 1.0.1

---

charts/cloudzero-agent/templates/_helpers.tpl
charts/cloudzero-agent/templates/cm.yaml
charts/cloudzero-agent/values.yaml

This adds a job to scrape metrics from the collector, and adds a lot of configuration for splitting out cost metrics from observability metrics. It was also designed to allow us to completely drop metrics and/or labels we're not interested in.
In order for the collector to know what to do with the metrics, the Gator accepts several lists of filters in its configuration. Those lists are configured in this …

CP-25384, CP-25375: cost/observability metrics split in Gator, scraping Gator metrics in Prometheus

---

charts/cloudzero-agent/templates/deploy.yaml

Allows custom resource configuration for init containers

Allow custom configuration for validator initcontainer resources

---

.github/workflows/build-and-publish-chart.yml

mirroring a change made to the `release/1.0.3` branch to allow us to release off of branches

checkout release branch to upload docs

---

.github/workflows/dont-change-agent-chart.yml

This just adds a quick status check which will fail if your commit touches anything in the charts/cloudzero-agent directory when committing to any branch other than develop, which is excluded so commits mirrored from charts/cloudzero-agent-validator don't cause the check to fail.
>
> - …

CP-27613: add action to ensure agent chart isn't changed here

---

.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/dont-change-agent-chart.yml

We use PRs for everything in this repo, *except* for changes being mirrored to this repo from the agent repo, which is the one thing we don't really want to check. Triggering this workflow only on PRs should give us the desired behavior in a much cleaner way than trying to condition it on the branch name, especially since GitHub likes to set the branch name to the target of the PR...
> Include any links …

CP-28969: only run dont-change-agent-chart action on PRs

---

.github/workflows/build-and-publish-beta-chart.yml
.github/workflows/build-and-publish-chart.yml

This works around a bug in v2.3.0, which seems to be broken.  See https://github.com/softprops/action-gh-release/issues/628 for details.

CP-29708: pin softprops/action-gh-release to v2.2.2
