index.yaml

update index.yaml to use public URL

update index.yaml to use public URL

---

.github/workflows/build-and-publish-chart.yml

CP-17269 - added GitHub action to package and release helm chart
N/A

adding build and release workflow

---

charts/cloudzero-agent/CHANGELOG.md
charts/cloudzero-agent/README.md
charts/cloudzero-agent/templates/_helpers.tpl
charts/cloudzero-agent/templates/cm.yaml
charts/cloudzero-agent/templates/deploy.yaml
charts/cloudzero-agent/templates/pvc.yaml
charts/cloudzero-agent/templates/secret.yaml
charts/cloudzero-agent/values.yaml

Updates based on Beta Feedback
See CHANGELOG.md
Can be tested using helm lint or running helm with the --debug flag

Updates based on beta feedback. See CHANGELOG.md for notes

---

CONTRIBUTING.md

This is a contributing guide for doing development against the public repository with basic guidelines for developer success.
Peer review

adding contributing guide

---

charts/cloudzero-agent/templates/deploy.yaml

The previous PR accidentally introduced a duplicate `resource` block definition for the `"cloudzero-agent-server"`. 
Albeit a safe mistake, this PR removes the duplicate definition.
<details>
<summary>Manual Testing Results</summary>
This PR CI is the testing, however if you'd like to run it manually do the following:
```bash
git clone git@github.com:josephbarnett/cloudzero-charts.git cloudzero-charts-jb
cd cloudzero-charts-jb
git checkout CP-19508-remove-dup-resource-def
act -j test_chart_lint 
```
**RESULTS**
```bash
INFO[0000] Using docker host 'unix:///var/run/docker.sock', and daemon socket 'unix:///var/run/docker.sock' 
[has_changes/detection_rules/scanner] 🚀  Start image=catthehacker/ubuntu:act-latest
[has_changes/detection_rules/scanner]   🐳  docker pull …
```

CP-19508: remove duplicate resource block in server deployment definition

---

README.md

> Describe the purpose of this PR along with any background information and the impacts of the proposed change. For the benefit of the community, please do not assume prior context.
>
> Provide details that support your chosen implementation, including: breaking changes, alternatives considered, changes to the API, etc.
>
> If the UI is being changed, please provide screenshots.
Readme update to fix the dead link to the contribution guide

Update README.md - fix dead link to contributing guide

---

charts/cloudzero-agent/README.md

A customer asked about "region", saying 
> What should i put there? The AWS region name of our clusters or is this something else?
This change to the readme is supposed to answer that question for them, let me know if disagree / want something better / different.

Update readme with examples of region

---

charts/cloudzero-agent/README.md

users that use our metrics exporters but want to use their own images might appreciate this bit of documentation
N/A

CP-19793: add image repo information to readme

---

charts/cloudzero-agent/README.md

Our KSM documentation for adding pod labels needs to be updated.
N/A

CP-19869: update KSM labels documentaion

---

.github/workflows/build-and-publish-chart.yml

1. Reorder when we create the version 
2. add steps to get the next version before creating it
These are important because when using the `flatherskevin/semver-action@v1` action - it will cause the tagged code to diverge from the updates we are making during release to the Chart.yml file. This can be seen here for release 0.0.12 - we never capture the correct chart version!
> https://github.com/Cloudzero/cloudzero-charts/blob/0.0.12/charts/cloudzero-agent/Chart.yaml#L5
I tested this first thought creating a simple test.yml workflow as follows:
```yaml
on:
push:
jobs:
generate:
permissions:
contents: 'write'
packages: 'write'
id-token: write
actions: 'read'
runs-on: ubuntu-latest
steps: 
- uses: actions/checkout@v1
- name: 'Get Previous tag'
id: previoustag
uses: …
```

Cp 20006 improve cloudzero charts release workflow

---

charts/cloudzero-agent/CHANGELOG.md
charts/cloudzero-agent/values.schema.json

The regex used to validate clusterName was incorrect. [According to the k8s docs here](https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#dns-subdomain-names) they `contain no more than 253 characters` . Therefore, the previous regex was incorrect, because it allows for 255 characters.
Mostly this is just to be consistent with the [CZ metrics …

CP 19246: Consistent Cluster Name Validation

---

.github/workflows/build-and-publish-chart.yml

Ensure we have the current README and docs for GH Pages when releasing

CP-20316 publish doc updates to Pages on Release

---

.github/workflows/build-and-publish-chart.yml
README.md
charts/cloudzero-agent/CHANGELOG.md

1. Update change log to catch up with recent changes
2. Fix release icon in README

Cp 20316 update README icon and change.log file

---

charts/cloudzero-agent/templates/_helpers.tpl

* Improve cleanString
Testing involved the following:
1. Create a template file (as outlined in the scenarios below)
2. Install the chart using the `scenario.yaml` values file
```sh
helm install cloudzero-agent . --namespace $NS -f scenario-values.yaml
```
3. Render the scrape configuration ConfigMap:
```sh
kubectl -n $NS describe configmap cloudzero-agent-configuration
```
> Look at the value for `remote_write: -url`. Make sure it has no special characters.
4. Render the validator configMap:
```sh
kubectl -n $NS describe configmap cloudzero-agent-configuration
```
> Look at the values ensuring no special characters.
**Base values config**
```yaml
cloudAccountId: |-
"\"1234567890\" ? - !~=+_()[]{}\\|:;<,>.?/"
clusterName: local-workshop-cirrus-rancher
region: "\"us-east-2\"" …
```

improve clean string

---

charts/cloudzero-agent/values.yaml

This PR pins the version of the CloudZero Agent Validator to avoid pulling the latest version, if breaking changes have been introduced. 
- [n/a] I have added documentation for new/changed functionality in this PR

CP-22169: Pin Validator Version

---

charts/cloudzero-agent/README.md

This PR updates the CloudZero Agent Helm Chart README to explain how to find the releases page, how to enable release notifications by watching the repo, and how to use `helm repo update`.
See CP-22334.

CP-22334 Document how to watch repo, update helm chart

---

charts/cloudzero-agent/values.yaml

Updated validator chart version to mitigate CVEs
> Describe how this can be tested by reviewers. Be specific about anything not tested and reasons why. If this library has unit and/or integration testing, tests should be added for new functionality and existing tests should complete without errors.
>
> Please include any manual steps for testing end-to-end or functionality not covered by unit/integration …

CP-22962 update validator chart version

---

.github/workflows/build-and-publish-beta-chart.yml

1. update beta release flow to publish to helm repo file.
* Index File: https://helm.sh/docs/topics/chart_repository/#add-new-charts-to-an-existing-repository
* Making the chart available through GH Pages: https://helm.sh/docs/topics/chart_repository/#add-new-charts-to-an-existing-repository
* Release management - with Index.yaml: https://helm.sh/docs/topics/chart_repository/#add-new-charts-to-an-existing-repository
* Share your charts with others - they need the webpage : https://helm.sh/docs/topics/chart_repository/#add-new-charts-to-an-existing-repository
Can only be tested in CI/CD

CP-22609: publish beta chart to helm index.yaml

---

charts/cloudzero-agent/docs/releases/1.0.1-beta.md

[CP-23423] 1.0.1-beta - bugfixes and improvements

---

charts/cloudzero-insights-controller/Chart.yaml
charts/cloudzero-insights-controller/templates/cm.yaml
charts/cloudzero-insights-controller/templates/init-job.yaml
charts/cloudzero-insights-controller/values.yaml

Ensures that a reasonable default is set for the parameter

[CP-23425] add default remote write retries

---

.github/workflows/build-and-publish-beta-chart.yml

package both charts in beta release - required because we use a subchart for these beta versions
fixes: https://github.com/Cloudzero/cloudzero-charts/actions/runs/11943904046/job/33293846839

CP-22730: package both charts in beta release

---

.github/workflows/build-and-publish-beta-chart.yml

fixes the beta workflow issue: https://github.com/Cloudzero/cloudzero-charts/actions/runs/11944152704

[CP-22730] fix name

---

charts/cloudzero-agent/docs/releases/1.0.0-beta-5.md
charts/cloudzero-agent/templates/insights-deploy.yaml
charts/cloudzero-agent/values.yaml

- **[CP-23892](https://cloudzero.atlassian.net/browse/CP-23892): Add healthcheck**
- **[CP-24009](https://cloudzero.atlassian.net/browse/CP-24009): Auto-detect API token rotations**
- **[CP-23959](https://cloudzero.atlassian.net/browse/CP-23959): Auto-detect TLS Cert rotations**
- **Add release notes for `1.0.0-beta-5`**
- **Update insights controller version**
TBD
[CP-23892]: https://cloudzero.atlassian.net/browse/CP-23892?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CP-24009]: https://cloudzero.atlassian.net/browse/CP-24009?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CP-23959]: https://cloudzero.atlassian.net/browse/CP-23959?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJw …

CP 23892 add healthcheck

---

charts/cloudzero-agent/docs/releases/1.0.0-beta-5.md
charts/cloudzero-agent/templates/_helpers.tpl
charts/cloudzero-agent/templates/cm.yaml
charts/cloudzero-agent/templates/insights-deploy.yaml
charts/cloudzero-agent/values.yaml

1. Updated insights controller to version 0.0.6
1. Changes to distribute pod replicas to different nodes (best effort)
2. Allow override of scrape target for KMS (DVAG beta feedback)
3. Release notes for cumulative changes
1. Deployment
```sh
helm upgrade --install cloudzero-agent . -f override.yaml
Release "cloudzero-agent" has been upgraded. Happy Helming!
NAME: cloudzero-agent
LAST DEPLOYED: Mon Dec 16 17:09:54 2024
NAMESPACE: default
STATUS: deployed
REVISION: 6
TEST SUITE: None
```
2. Inspect deployment
````yaml
apiVersion: apps/v1
kind: Deployment
metadata:
annotations:
deployment.kubernetes.io/revision: "3"
meta.helm.sh/release-name: cloudzero-agent
meta.helm.sh/release-namespace: default
creationTimestamp: "2024-12-16T19:58:05Z"
generation: 3
labels:
app.kubernetes.io/component: …
```

CP-24118: affinity settings, release notes

---

charts/cloudzero-agent/README.md

This PR updates the README to include recommended knowledge for an optimal installation experience.

CP-23452 document required install skills

---

.github/workflows/build-and-publish-beta-chart.yml

> Describe the purpose of this PR along with any background information and the impacts of the proposed change. For the benefit of the community, please do not assume prior context.
>
> Provide details that support your chosen implementation, including: breaking changes, alternatives considered, changes to the API, etc.
>
> If the UI is being changed, please provide screenshots.
> Include any links supporting …

CP-24668: add missing workflow steps

---

charts/cloudzero-agent/docs/releases/1.0.0-beta-7.md

adding the upgrade helm command to the beta-7 release notes

CP-24725: Add upgrade command to beta-7 release notes

---

charts/cloudzero-agent/docs/releases/1.0.0-rc1.md

CP-25115: add release notes for 1.0.0-rc1 release

---

.github/workflows/build-and-publish-chart.yml

we want to release RC1 to the main repo, but the `develop` chart release workflow needs the changes added to the beta workflow in branch `release/1.0.0`

CP-25165: update to match beta release workflow

---

.github/workflows/build-and-publish-chart.yml

CP-25165: checkout branches in correct order

---

.github/workflows/test-chart.yml
charts/cloudzero-agent/docs/cert-trouble-shooting.md

CP-25270: prepare release/1.0.0 for merging

---

charts/cloudzero-agent/README.md

1. Minor change for default values, which are important for different types of kubernetes resources (aka deployment)
2. Fix alignment of recommendations
3. Remove official documentation duplication
> Describe how this can be tested by reviewers. Be specific about anything not tested and reasons why. If this library has unit and/or integration testing, tests should be added for new functionality and existing tests should complete without errors.
>
> Please include any manual steps for testing end-to-end or functionality not covered by unit/integration tests.
>
> Also include details of the environment this PR was developed in (language/platform/browser version).

CP-25353: ensure defaults for example are correct, simply README

---

charts/cloudzero-agent/docs/secret-store-operator-aws-example.md

CP-25697: Update secret-store-operator-aws-example.md

---

charts/cloudzero-agent/docs/releases/1.0.0-rc2.md

- updates the release docs to use the correct release name

CP-25822: update docs to use correct release name

---

charts/cloudzero-agent/docs/releases/1.0.0-beta-1.md
charts/cloudzero-agent/docs/releases/1.0.0-beta-10.md
charts/cloudzero-agent/docs/releases/1.0.0-beta-2.md
charts/cloudzero-agent/docs/releases/1.0.0-beta-3.md
charts/cloudzero-agent/docs/releases/1.0.0-beta-4.md
charts/cloudzero-agent/docs/releases/1.0.0-beta-5.md
charts/cloudzero-agent/docs/releases/1.0.0-beta-6.md
charts/cloudzero-agent/docs/releases/1.0.0-beta-7.md
charts/cloudzero-agent/docs/releases/1.0.0-beta-8.md
charts/cloudzero-agent/docs/releases/1.0.0-beta-9.md
charts/cloudzero-agent/docs/releases/1.0.0-beta.md
charts/cloudzero-agent/docs/releases/1.0.0-rc1.md
charts/cloudzero-agent/docs/releases/1.0.0-rc2.md
charts/cloudzero-agent/docs/releases/1.0.0-rc3.md
charts/cloudzero-agent/docs/releases/1.0.0-rc4.md
charts/cloudzero-agent/docs/releases/1.0.0.md

Some of our links reference the wrong repository.

[CP-26018] Fix broken links for comparing versions

---

charts/cloudzero-agent/docs/releases/1.0.1.md
docs/releases/RELEASE_PROCESS.md

adding release notes for 1.0.1

CP-26389: add release notes for 1.0.1

---

charts/cloudzero-agent/templates/_helpers.tpl
charts/cloudzero-agent/templates/cm.yaml
charts/cloudzero-agent/values.yaml

This primarily adapts to this change in insights-controller: https://github.com/Cloudzero/cloudzero-insights-controller/pull/223
Note that we shouldn't merge this yet; once we have an insights-controller release we can merge this *and* update the image tag to that version. As is this will just break everything...
>
> - GitHub Issue/PR number addressed or …

CP-27063: have insights-controller send data to Gator when appropriate

---

charts/cloudzero-agent/docs/releases/1.1.0-beta-2.md

Add some release notes for 1.1.0-beta-2.
>
> - Support forum thread
> - Related pull requests/issues from other repos
>
> If there are no references, simply delete this section.
> Describe how this can be tested by reviewers. Be specific about anything not tested and reasons why. If this …

CP-27466: add release notes for 1.1.0-beta-2

---

charts/cloudzero-agent/docs/upgrades.md
charts/cloudzero-agent/templates/_helpers.tpl
charts/cloudzero-agent/templates/cm.yaml
charts/cloudzero-agent/templates/init-job.yaml
charts/cloudzero-agent/templates/insights-deploy.yaml
charts/cloudzero-agent/values.yaml

includes:
- https://github.com/Cloudzero/cloudzero-charts/pull/188
- parts of https://github.com/Cloudzero/cloudzero-charts/pull/187/files
- for using the 0.2.1 image
in progress

CP-27474: prepare 1.0.3 release

---

charts/cloudzero-agent/docs/releases/1.0.3.md

adds a release note for the 1.0.3 patch release

CP-27474: add 1.0.3 release note

---

README.md

removing the `helm upgrade` from the top level readme to prevent confusion for users

CP-27517: update top-level docs for clarity

---

charts/cloudzero-agent/Chart.yaml
charts/cloudzero-agent/docs/releases/1.1.1.md
charts/cloudzero-agent/templates/clusterrole.yaml
charts/cloudzero-agent/templates/init-job.yaml
charts/cloudzero-agent/values.yaml

This just merges develop into main, cleaning up any conflicts. Once this is done my hope is that the release workflow should work moving forward...
>
> - Support forum thread
> - Related pull requests/issues from other repos
>
> If there are no references, simply delete this section.
> …

CP-28708: merge 'develop' into 'main'

---

.github/workflows/build-and-publish-beta-chart.yml
.github/workflows/build-and-publish-chart.yml

Please note that changes to the `cloudzero-agent` Helm chart should be made instead in the [`helm directory`](https://github.com/Cloudzero/cloudzero-agent/tree/develop/helm) in the [cloudzero-agent repository](https://github.com/Cloudzero/cloudzero-agent/), and will automatically be mirrored to this repository as soon as they are merged.
This just removes the requirement for an approval prior to making a …

CP-29766: remove requirement for approval when making a release
